### ISSUE TITLE
Multiple words please

### ISSUE THREAD

**Issue by Mehul** [nikhilhex/passwordle-generator#11]
As mentioned in this XKCD article: https://xkcd.com/936/

Four random common words together are stronger and tougher to crack. 

Can you make four random common word combinations please?

**Comment by sleeepstorm** [comment]
Hi, i've fixed the issue. The PR I linked wasn't a fix but the next one is.

**Comment by sleeepstorm** [comment]
Now the issue is fixed, i made some commits but not any PRs

**Comment by Mehul** [comment]
That's great, thanks!
